apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-app
  namespace: application
  labels:
    app: spring-boot-app
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - application
  selector:
    matchLabels:
      prometheus: "true"
  endpoints:
  - port: http
    path: /prometheus
